version: '3'

tasks:
  init:
    desc: 'Initialize Terraspace'
    cmds:
      - terraspace init
    silent: false

  validate:
    desc: 'Validate Terraform code'
    cmds:
      - terraspace validate
    silent: false

  format:
    desc: 'Format Terraform code'
    cmds:
      - terraform fmt -recursive
    silent: false

  checkov:
    desc: 'Run checkov'
    cmds:
      - checkov --download-external-modules -o junitxml --framework terraform -d ./ > checkov.xml
    silent: false

  tfsec:
    desc: 'Run tfsec'
    cmds:
      - tfsec ./ --format junit --out tfsec-junit.xml
    silent: false

  summary:
    desc: 'Display summary'
    cmds:
      - echo "Validation and checks have been completed."

  deploy:
    desc: 'Run all tasks'
    deps: [init, validate, format, checkov, tfsec, summary]
    silent: false
