version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
      python: $PYTHON_VERSION

    commands:
      - "apt update -y"
      - "apt install -y libxss1 libappindicator3-1 libindicator7 fonts-liberation libdbus-1-3"
      - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      - "apt install -y ./google-chrome*.deb"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - "cd /codebuild-user/website"
      - "npm install -g pnpm"
      - "pnpm install --frozen-lockfile"
      - "echo #### Owner Change"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/codebuild_user_owner_change.sh"

  build:
    run-as: "codebuild-user"
    commands:
      - "echo #### Set up environment"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_env.sh"
      - "env"
      - "echo #### Test LightHouse Mobile"
      - "export LHCI_MOBILE_RUN=true && pnpm run lighthouse:mobile"
    finally:
      - "python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/reports.py"
      - 'aws lambda invoke --function-name "ci-cd-website-$ENVIRONMENT-reports-notification" --cli-binary-format raw-in-base64-out --payload file://payload.json output.txt'

artifacts:
  files:
    - "/codebuild-user/website/lhci-reports-mobile/**/*"

cache:
  paths:
    - "/bin"
    - "/usr/local/bin"
    - "/codebuild-user/website/node_modules"
    - "/root/.cache"
    - "/usr/local/bundle"
