version: 0.2

env:
  variables:
    ACCOUNT_ID: $ACCOUNT_ID
    ENVIRONMENT: $ENVIRONMENT
    TEST_REPORTS_BUCKET: $TEST_REPORTS_BUCKET
    LHCI_REPORTS_BUCKET: $LHCI_REPORTS_BUCKET
    WEBSITE_GIT_REPOSITORY_LINK: $WEBSITE_GIT_REPOSITORY_LINK

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/install_packages.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/setup_docker.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/configure_dind.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/setup_makefile_targets.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/add_prod_targets.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/batch_lhci_targets.sh"
      - "cd ${CODEBUILD_SRC_DIR}/website"

  build:
    commands:
      - "echo #### Set up environment"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_env.sh"
      - "echo #### Test LightHouse Mobile"
      - "DIND=1 make lighthouse-mobile"
    finally:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/run_reports.sh"

artifacts:
  files:
    - "website/lhci-reports-mobile/**/*"
