version: 0.2

phases:
  pre_build:
    commands:
      - echo "Run docker daemon"
      - dockerd-entrypoint.sh &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

      - echo "Check Docker Compose availability"
      - (docker compose version || docker-compose --version) || \
        (echo "Docker Compose is missing! Install the Compose plugin or legacy CLI." && exit 1)

      - echo "cd to website folder"
      - cd /codebuild-user/website

  build:
    run-as: codebuild-user
    commands:
      - echo "Running Lighthouse Desktop tests"
      - export LHCI_DESKTOP_RUN=true
      - export CI=1
      - make lighthouse-desktop

    finally:
      - "python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/reports.py"
      - 'aws lambda invoke --function-name "ci-cd-website-$ENVIRONMENT-reports-notification" --cli-binary-format raw-in-base64-out --payload file://payload.json output.txt'

artifacts:
  files:
    - "/codebuild-user/website/lhci-reports-desktop/**/*"

cache:
  paths:
    - "/bin"
    - "/usr/local/bin"
    - "/codebuild-user/website/node_modules"
    - "/root/.cache"
    - "/usr/local/bundle"
