version: 0.2

env:
  variables:
    DIND: "1"
    ACCOUNT_ID: $ACCOUNT_ID
    ENVIRONMENT: $ENVIRONMENT
    TEST_REPORTS_BUCKET: $TEST_REPORTS_BUCKET
    LHCI_REPORTS_BUCKET: $LHCI_REPORTS_BUCKET
    WEBSITE_GIT_REPOSITORY_LINK: $WEBSITE_GIT_REPOSITORY_LINK

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/install_packages.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/setup_docker.sh"

  build:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_env.sh"
      - echo "🔍 Running linting checks with new batch script"
      - cd ${CODEBUILD_SRC_DIR}/website
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/batch_unit_mutation_lint.sh lint-all"
    finally:
      - echo "📊 Generating test reports"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/run_reports.sh"

artifacts:
  files:
    - "website/lint-logs/**/*"
