version: 0.2

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - "echo #### Owner Change"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/codebuild_user_owner_change.sh"

  build:
    run-as: "codebuild-user"
    commands:
      - "mkdir ${CODEBUILD_SRC_DIR}/website/lint-logs"
      - "echo #### Running Lint"
      - "make lint-next 2>&1 | tee lint-logs/next.log"
      - "make lint-tsc | tee lint-logs/tsc.log"
      - "make lint-md | tee lint-logs/md.log"

artifacts:
  files:
    - "${CODEBUILD_SRC_DIR}/website/lint-logs/**/*"
