version: 0.2

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/install_packages.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/setup_docker.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/configure-dind.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/setup_makefile_targets.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/add_prod_targets.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/batch_unit_mutation_lint_targets.sh"

  build:
    commands:
      - echo "ðŸ” Running lint checks with built-in DIND support"
      - cd ${CODEBUILD_SRC_DIR}/website
      - mkdir -p lint-logs
      - DIND=1 make lint-next 2>&1 | tee lint-logs/next.log
      - DIND=1 make lint-tsc 2>&1 | tee lint-logs/tsc.log
      - DIND=1 make lint-md 2>&1 | tee lint-logs/md.log

artifacts:
  files:
    - "website/lint-logs/**/*"
