version: 0.2

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"

  build:
    commands:
      - "mkdir -p ${CODEBUILD_SRC_DIR}/website/lint-logs"
      - "echo #### Running Lint"
      - "cd ${CODEBUILD_SRC_DIR}/website"
      - "DIND=1 make lint-next 2>&1 | tee ${CODEBUILD_SRC_DIR}/website/lint-logs/next.log"
      - "DIND=1 make lint-tsc | tee ${CODEBUILD_SRC_DIR}/website/lint-logs/tsc.log"
      - "DIND=1 make lint-md | tee ${CODEBUILD_SRC_DIR}/website/lint-logs/md.log"

artifacts:
  files:
    - "${CODEBUILD_SRC_DIR}/website/lint-logs/**/*"
