version: 0.2

env:
  variables:
    ACCOUNT_ID: $ACCOUNT_ID
    ENVIRONMENT: $ENVIRONMENT
    TEST_REPORTS_BUCKET: $TEST_REPORTS_BUCKET
    LHCI_REPORTS_BUCKET: $LHCI_REPORTS_BUCKET
    WEBSITE_GIT_REPOSITORY_LINK: $WEBSITE_GIT_REPOSITORY_LINK

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - "export DIND=1 && . ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/k6_installation.sh"
      - "cd ${CODEBUILD_SRC_DIR}/website"

  build:
    commands:
      - "echo #### Set up environment"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_env.sh"
      - "echo #### Running Load Test" # Reports folder: src/test/load/results/
      - "DIND=1 make load-tests"
    finally:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/run_reports.sh"

artifacts:
  files:
    - "${CODEBUILD_SRC_DIR}/website/src/test/load/results/**/*"
