version: 0.2

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - "cd ${CODEBUILD_SRC_DIR}/website"

  build:
    commands:
      - "mkdir -p ${CODEBUILD_SRC_DIR}/website/memory-leak-logs"
      - "echo #### Set up environment"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_env.sh"
      - "echo #### Running Memory Leak Test" # No Reports folder
      - "DIND=1 make test-memory-leak 2>&1 | tee ${CODEBUILD_SRC_DIR}/website/memory-leak-logs/memory-leak.log"
    finally:
      - "${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/run_reports.sh"

artifacts:
  files:
    - "${CODEBUILD_SRC_DIR}/website/memory-leak-logs/**/*"
