version: 0.2

phases:
  pre_build:
    commands:
      - echo "Start Docker daemon"
      - dockerd-entrypoint.sh &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

      - echo "cd to website folder"
      - cd /$CODEBUILD_SRC_DIR/website

  build:
    run-as: codebuild-user
    commands:
      - echo "Running Mutation Test"
      - export MUTATION_RUN=true
      - make test-mutation
      - mv /codebuild-user/website/reports/mutation/mutation.html /codebuild-user/website/reports/mutation/index.html

    finally:
      - python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/reports.py
      - 'aws lambda invoke --function-name "ci-cd-website-$ENVIRONMENT-reports-notification" --cli-binary-format raw-in-base64-out --payload file://payload.json output.txt'

artifacts:
  files:
    - "/codebuild-user/website/reports/**/*"

cache:
  paths:
    - "/bin"
    - "/usr/local/bin"
    - "/codebuild-user/website/node_modules"
    - "/root/.cache"
    - "/usr/local/bundle"
