version: 0.2

env:
  variables:
    WEBSITE_GIT_REPOSITORY_LAST_COMMIT_SHA: "dummy-sha"

phases:
  pre_build:
    commands:
      - echo "Checking Docker status"
      - docker info || (echo "Docker daemon not available. Please check configuration." && exit 1)
      - echo "cd to website folder"
      - cd /codebuild-user/website || exit 1

  build:
    run-as: codebuild-user
    commands:
      - echo "Running Unit Tests"
      - export UNIT_RUN=true
      - make test-unit-all || echo "No unit test target to run"

    finally:
      - echo "Running reports script"
      - python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/reports.py || echo "Report script failed but build will continue"
      - |
        aws lambda invoke \
          --function-name "ci-cd-website-$ENVIRONMENT-reports-notification" \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json output.txt || echo "Lambda notification failed"

artifacts:
  files:
    - "/codebuild-user/website/coverage/**/*"

cache:
  paths:
    - "/bin"
    - "/usr/local/bin"
    - "/codebuild-user/website/node_modules"
    - "/root/.cache"
    - "/usr/local/bundle"
