version: 0.2

phases:
  build:
    run-as: codebuild-user
    commands:
      - echo "Running Unit Tests"
      - make test-unit-all || echo "No unit test target to run"

    finally:
      - echo "Running reports script"
      - python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/reports.py || echo "Report script failed but build will continue"
      - |
        aws lambda invoke \
          --function-name "ci-cd-website-$ENVIRONMENT-reports-notification" \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json output.txt || echo "Lambda notification failed"

artifacts:
  files:
    - "${CODEBUILD_SRC_DIR}/coverage/**/*"
