version: 0.2

env:
  variables:
    ACCOUNT_ID: $ACCOUNT_ID
    ENVIRONMENT: $ENVIRONMENT
    TEST_REPORTS_BUCKET: $TEST_REPORTS_BUCKET
    LHCI_REPORTS_BUCKET: $LHCI_REPORTS_BUCKET
    WEBSITE_GIT_REPOSITORY_LINK: $WEBSITE_GIT_REPOSITORY_LINK

phases:
  install:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/install_packages.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/setup_docker.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/configure-dind.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/setup_makefile_targets.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/add_prod_targets.sh"
      - ". ${CODEBUILD_SRC_DIR}/website/scripts/ci/batch_unit_mutation_lint_targets.sh"

  build:
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_env.sh"
      - echo "🚀 Running unit tests with built-in DIND support"
      - cd ${CODEBUILD_SRC_DIR}/website
      - DIND=1 make test-unit-all
    finally:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/run_reports.sh"

artifacts:
  files:
    - "website/**/*"
