version: 0.2

phases:
  install:
    commands:
      - '/bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/credentials.sh'
      - 'export AWS_PROFILE=terraform'
      - 'touch ~/.bash_profile'
      - 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
      - 'export NVM_DIR="$HOME/.nvm"'
      - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
      - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
      - 'nvm install 21'
      - 'node -v'
      - 'npm -v'
      - 'cd ~'
      - 'git clone https://github.com/VilnaCRM-Org/website.git'
      - 'cd website/'
      - 'yum install -y yum-utils'
      - 'echo #### Install pnpm'
      - 'npm install -g pnpm'
      - 'echo #### Install dependencies'
      - 'pnpm i --frozen-lockfile'

  build:
    commands:
      - 'echo #### Build Project'
      - 'pnpm run build'
      - 'echo #### Deploy Project'
      - 'aws s3 sync ./out s3://$BUCKET_NAME'
      - 'echo "Content install succeeded"'

artifacts:
  files:
    - '**/*'
