version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/credentials.sh'
      - 'n install 21.7.1'
      - 'cd ~'
      - 'git clone https://github.com/VilnaCRM-Org/website.git'
      - 'cd website/'
      - 'yum install -y yum-utils'
      - 'echo #### Install pnpm'
      - 'npm install -g pnpm'
      - 'echo #### Install dependencies'
      - 'pnpm i --frozen-lockfile'

  build:
    commands:
      - 'echo #### Build Project'
      - 'pnpm run build'
      - 'echo #### Deploy Project'
      - 'aws s3 sync ./out s3://$BUCKET_NAME'
      - 'echo "Content install succeeded"'

artifacts:
  files:
    - '**/*'
