version: 0.2

env:
  variables:
    CODE_SRC_DIR: '.'
    TF_VERSION: '1.6.6'

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      ruby: $RUBY_VERSION
    commands:
      - 'yum install -y yum-utils'
      - 'yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo'
      - 'yum -y install terraform'
      - 'bundle install --gemfile ${CODEBUILD_SRC_DIR}/terraform/Gemfile'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}/terraform'
      - 'terraspace all down -y'

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
