version: 0.2

env:
  variables:
    SCRIPT_DIR: './aws/scripts'
    TFSEC_VERSION: 'v1.28.5'
    PYTHON_VERSION: '3.12'
    GOLANG_VERSION: '1.21'
    RUBY_VERSION: '3.2'

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      golang: $GOLANG_VERSION
      ruby: $RUBY_VERSION
    commands:
      - 'yum install -y yum-utils'
      - '/bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/terraform_installation.sh'
      - 'yum update -y'
      - 'export PATH="$HOME/.tfenv/bin:$PATH"'
      - 'yum install -y jq awscli'
      - 'pip3 install checkov'
      - 'yum install -y golang'
      - 'wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64'
      - 'chmod +x ./tfsec'
      - 'mv ./tfsec /usr/local/bin/tfsec'
      - 'bundle install --gemfile ${CODEBUILD_SRC_DIR}/terraform/Gemfile'
      - 'sudo snap install task --classic'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}/terraform'
      - 'echo ## VALIDATION : Starting ...'
      - 'mkdir -p ${CODEBUILD_SRC_DIR}/reports'
      - 'task deploy -t ${CODEBUILD_SRC_DIR}/task/Taskfile.yml'
      - 'cp checkov.xml ${CODEBUILD_SRC_DIR}/reports/checkov.xml'
      - 'cp tfsec-junit.xml ${CODEBUILD_SRC_DIR}/reports/tfsec-junit.xml'

artifacts:
  files:
    - '**/*'

reports:
  checkov-reports:
    files:
      - './reports/checkov.xml'
    file-format: 'JUNITXML'
  tfsec-reports:
    files:
      - './reports/tfsec-junit.xml'
    file-format: 'JUNITXML'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
