version: 0.2

env:
  variables:
    HURL_DIR: './hurl'
    HURL_VERSION: '4.2.0'
    INSTALL_DIR: '/tmp'

phases:
  build:
    commands:
      - 'curl --silent --location https://github.com/Orange-OpenSource/hurl/releases/download/$HURL_VERSION/hurl-$HURL_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xvz -C $INSTALL_DIR'
      - 'export PATH=$PWD$INSTALL_DIR/hurl-$HURL_VERSION:$PATH'
      - 'echo ## Test Website Connection...'
      - 'hurl --test --variable website_url=$WEBSITE_URL ${CODEBUILD_SRC_DIR}/${HURL_DIR}/$TS_ENV/healthcheck.hurl'

artifacts:
  files:
    - '**/*'
