version: 0.2

env:
  variables:
    CODE_SRC_DIR: '.'
    TF_VERSION: '1.6.6'
    PYTHON_VERSION: '3.12'
    RUBY_VERSION: '3.2'

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      ruby: $RUBY_VERSION
    commands:
      - '/bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/credentials.sh'
      - 'yum install -y yum-utils'
      - '/bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/terraform_installation.sh'
      - 'export PATH="$HOME/.tfenv/bin:$PATH"'
      - 'bundle install --gemfile ${CODEBUILD_SRC_DIR}/terraform/Gemfile'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}/terraform'
      - 'echo ## TERRASPACE PLAN : Generate the Terraform Plan'
      - 'terraspace plan website --out "website.plan"'
      - 'terraspace plan ci-cd-infrastructure --out "ci-cd-infrastructure.plan"'

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
