version: 0.2

env:
  variables:
    TFSEC_VERSION: 'v1.28.5'
    GOLANG_VERSION: '1.21'

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      golang: $GOLANG_VERSION
      ruby: $RUBY_VERSION
    commands:
      - 'echo ## Install OpenTofu'
      - 'curl --proto "=https" --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh'
      - 'chmod +x install-opentofu.sh'
      - './install-opentofu.sh --install-method rpm'
      - 'rm install-opentofu.sh'
      - 'echo ## Install Terraspace'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/credentials.sh'
      - 'yum install -y yum-utils'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/terraform_installation.sh'
      - 'bundle install --gemfile ${CODEBUILD_SRC_DIR}/terraform/Gemfile'
      - 'yum update -y'
      - 'echo ## Install Validation Software'
      - 'pip3 install checkov'
      - 'curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash'
      - 'go install github.com/go-task/task/v3/cmd/task@latest'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}/terraform'
      - 'echo ## VALIDATION : Starting ...'
      - 'mkdir -p ${CODEBUILD_SRC_DIR}/reports'
      - 'tofu login integrations/github'
      - 'cp ${CODEBUILD_SRC_DIR}/task/terraform_tests.yml ${CODEBUILD_SRC_DIR}/terraform/Taskfile.yml'
      - 'task --verbose summary'
      - 'cp checkov.xml ${CODEBUILD_SRC_DIR}/reports/checkov.xml'
      - 'cp tfsec-junit.xml ${CODEBUILD_SRC_DIR}/reports/tfsec-junit.xml'

artifacts:
  files:
    - '**/*'

reports:
  checkov-reports:
    files:
      - './reports/checkov.xml'
    file-format: 'JUNITXML'
  tfsec-reports:
    files:
      - './reports/tfsec-junit.xml'
    file-format: 'JUNITXML'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
