version: 0.2

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      ruby: $RUBY_VERSION
    commands:
      - 'echo ## Install Terraspace'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/credentials.sh'
      - 'dnf install -y yum-utils'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/terraform_installation.sh'
      - 'dnf update -y'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}/terraform'
      - 'echo ## TERRASPACE Init : Initialize all providers and modules'
      - 'terraspace all init'
      - 'echo ## TERRASPACE UP : Bringing up the infrastructure'
      - 'terraspace up ci-cd-infrastructure --plan "ci-cd-infrastructure.plan" -y'
      - 'terraspace up ci-cd-iam --plan "ci-cd-iam.plan" -y'
      - 'terraspace up website-iam --plan "website-iam.plan" -y'
      - 'terraspace up iam-groups --plan "iam-groups.plan" -y'

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
