version: 0.2

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      ruby: $RUBY_VERSION
    commands:
      - "echo ## Install Terraspace"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/credentials.sh"
      - "dnf install -y yum-utils"
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/terraform_installation.sh"
      - "dnf update -y"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}"
      - "echo ## TERRASPACE Init : Initialize all providers and modules"
      - "make terraspace-all-init"
      - "echo ## TERRASPACE UP : Bringing up the infrastructure"
      - 'make terraspace-up-plan stack="ci-cd-infrastructure" plan="ci-cd-infrastructure.plan"'
      - 'make terraspace-up-plan stack="ci-cd-iam" plan="ci-cd-iam.plan"'
      - 'make terraspace-up-plan stack="website-iam" plan="website-iam.plan"'
      - 'make terraspace-up-plan stack="iam-groups" plan="iam-groups.plan"'

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - "/bin"
    - "/usr/local/bin"
    - "/root/.terraform"
    - "/root/.cache"
    - "/root/.gem"
    - "/usr/local/bundle"
