version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION

    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh'
      - 'cd ~/website'

  build:
    commands:
      - 'echo #### Test LightHouse'
      - 'pnpm run format'
      - 'pnpm run lint:next'
      - 'pnpm run lint:tsc'
      - 'pnpm run lint:md'

artifacts:
  files:
    - '/root/website/**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/website/node_modules'
    - '/root/.cache'
    - '/usr/local/bundle'
