version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION

    commands:
      - 'echo #### Install Software'
      - 'apt update -y'
      - 'apt install -y libxss1 libappindicator3-1 libindicator7 fonts-liberation libdbus-1-3'
      - 'wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
      - 'apt install -y ./google-chrome*.deb'
      - 'n install 21.7.1'
      - 'cd ~'
      - 'git clone -b 5-make-website-layout https://github.com/VilnaCRM-Org/website.git'
      - 'cd website/'
      - 'echo #### Install pnpm'
      - 'npm install -g pnpm @lhci/cli@0.13.x'
      - 'echo #### Install dependencies'
      - 'pnpm i --frozen-lockfile'

  build:
    commands:
      - 'echo #### Test LightHouse Desktop'
      - 'lhci collect --url=https://$WEBSITE_URL --settings.preset=desktop --settings.chromeFlags="--no-sandbox" --psiStrategy=desktop'
      - 'lhci upload --target=filesystem --outputDir=lhci-reports-desktop'
      - 'echo #### Test LightHouse Mobile'
      - 'lhci collect --url=https://$WEBSITE_URL --settings.chromeFlags="--no-sandbox" --psiStrategy=mobile'
      - 'lhci upload --target=filesystem --outputDir=lhci-reports-mobile'

  post_build:
    commands:
      - 'mkdir ~/reports'
      - 'cp -r ~/website/lhci-reports-desktop ~/reports'
      - 'cp -r ~/website/lhci-reports-mobile ~/reports'

artifacts:
  files:
    - '**/*'
  base-directory: '~/reports'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
