version: 0.2

batch:
  fast-fail: false
  build-matrix:
    - identifier: lighthouse
      buildspec: buildspec_lighthouse.yml
      ignore-failure: false

    - identifier: playwright
      buildspec: buildspec_playwright.yml
      ignore-failure: false
