version: 0.2

env:
  variables:
    GOLANG_VERSION: '1.21'

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
      golang: $GOLANG_VERSION
    commands:
      - 'n install 21.7.1'
      - 'go install github.com/go-task/task/v3/cmd/task@latest'
      - 'cd ~'
      - 'git clone https://github.com/VilnaCRM-Org/website.git'
      - 'cd website/'
      - 'yum install -y yum-utils'
      - 'echo #### Install pnpm'
      - 'npm install -g pnpm'
      - 'rm .env'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/createEnv.sh $WEBSITE_URL'
      - 'echo #### Install dependencies'
      - 'pnpm i --frozen-lockfile'

  pre_build:
    commands:
      - 'echo #### Test Project'
      - 'pnpm run format'
      - 'pnpm run lint:next'
      - 'pnpm run lint:tsc'
      - 'pnpm run lint:md'
      - 'pnpm run test:e2e'
      - 'pnpm run test:mutation'
      - 'pnpm run test:visual'
      - 'pnpm run test:unit'
      - 'pnpm run test:memory-leak'
      - 'pnpm run lighthouse:desktop'
      - 'pnpm run lighthouse:mobile'

  build:
    commands:
      - 'echo #### Build Project'
      - 'pnpm run build'
      - 'echo #### Deploy Project'
      - 'aws s3 sync ./out s3://$BUCKET_NAME'
      - 'echo "Content install succeeded"'

artifacts:
  files:
    - '**/*'
