version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION

    commands:
      - 'echo #### Install Software'
      - 'n install 21.7.1'
      - 'cd ~'
      - 'git clone -b $WEBSITE_GIT_REPOSITORY_BRANCH "$WEBSITE_GIT_REPOSITORY_LINK.git"'
      - 'cd website/'
      - 'echo #### Install pnpm'
      - 'npm install -g pnpm'
      - 'echo #### Install dependencies'
      - 'pnpm i --frozen-lockfile'

  build:
    commands:
      - 'echo #### Test LightHouse'
      - 'pnpm run format'
      - 'pnpm run lint:next'
      - 'pnpm run lint:tsc'
      - 'pnpm run lint:md'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.cache'
    - '/usr/local/bundle'
