version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION

    commands:
      - 'echo #### Install Software'
      - 'n install 21.7.1'
      - 'cd ~'
      - 'git clone -b 5-make-website-layout https://github.com/VilnaCRM-Org/website.git'
      - 'cd website/'
      - 'echo #### Install pnpm'
      - 'npm install -g pnpm'
      - 'echo #### Install dependencies'
      - 'pnpm i --frozen-lockfile'
      - 'npx playwright install'
      - 'npx playwright install-deps'

  build:
    commands:
      - pnpm run test:e2e
      - pnpm run test:mutation
      - pnpm run test:visual
      - pnpm run test:unit
      - pnpm run test:memory-leak

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
