batch:
  build-matrix:
    static:
      ignore-failure: false
    dynamic:
      buildspec:
        - ./aws/buildspecs/website/buildspec_playwright.yml
        - ./aws/buildspecs/website/buildspec_lighthouse.yml
