version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
      python: $PYTHON_VERSION

    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh'
      - 'cd ~/website'
      - 'echo #### Set up environment'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/createEnv.sh'

  build:
    commands:
      - 'echo #### Running Unit Test' # Reports folder: coverage/lcov-report/
      - 'export UNIT_RUN=true && pnpm run test:unit'

    finally:
      - 'python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/reports.py'
      - 'aws lambda invoke --function-name "ci-cd-website-$ENVIRONMENT-reports-notification" --cli-binary-format raw-in-base64-out --payload file://payload.json output.txt'

artifacts:
  files:
    - '/root/website/coverage/**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/website/node_modules'
    - '/root/.cache'
    - '/usr/local/bundle'
