version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
      python: $PYTHON_VERSION
    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh'
      - 'cd /codebuild-user/website'

  build:
    run-as: 'codebuild-user'
    commands:
      - 'echo #### Set up environment'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/createEnv.sh'
      - 'echo #### Running Mutation Test' # Reports folder: reports/mutation/
      - 'export MUTATION_RUN=true && pnpm run test:mutation'
      - 'mv /codebuild-user/website/reports/mutation/mutation.html /codebuild-user/website/reports/mutation/index.html'

    finally:
      - 'python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/reports.py'
      - 'aws lambda invoke --function-name "ci-cd-website-$ENVIRONMENT-reports-notification" --cli-binary-format raw-in-base64-out --payload file://payload.json output.txt'

artifacts:
  files:
    - '/codebuild-user/website/reports/**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/codebuild-user/website/node_modules'
    - '/root/.cache'
    - '/usr/local/bundle'
