version: 0.2

env:
  variables:
    GOLANG_VERSION: '1.21'

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
      golang: $GOLANG_VERSION
    commands:
      - 'echo #### Install Software'
      - 'dnf install -y mesa-libgbm-devel yum-utils'
      - 'dnf update -y'
      - 'dnf install -y nginx'
      - 'curl http://localhost'
      - 'wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'
      - 'dnf install -y ./google-chrome-stable_current_*.rpm'
      - 'n install 21.7.1'
      - 'go install github.com/go-task/task/v3/cmd/task@latest'
      - 'cd ~'
      - 'git clone https://github.com/VilnaCRM-Org/website.git'
      - 'cd website/'
      - 'echo #### Install pnpm'
      - 'npm install -g pnpm'
      - 'echo #### Install dependencies'
      - 'pnpm i --frozen-lockfile'

  pre_build:
    commands:
      - 'rm .env'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/createEnv.sh localhost'
      - 'echo #### Build Project'
      - 'pnpm run build'
      - 'rm -r /usr/share/nginx/html/*'
      - 'cp -r ./out/. /usr/share/nginx/html/'
      - 'echo #### Test Project'
      - 'pnpm run test:e2e'
      - 'pnpm run test:mutation'
      - 'pnpm run test:visual'
      - 'pnpm run test:unit'
      - 'pnpm run test:memory-leak'
      # - 'cp ${CODEBUILD_SRC_DIR}/task/website_tests.yml ./Taskfile.yml'
      # - 'task --verbose summary'

  build:
    commands:
      - 'echo #### Build Project'
      - 'pnpm run build'
      - 'echo #### Deploy Project'
      - 'aws s3 sync ./out s3://$BUCKET_NAME'
      - 'echo "Content install succeeded"'

artifacts:
  files:
    - '**/*'
