version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh'
      - 'cd /codebuild-user/website'

  build:
    commands:
      - 'echo #### Build Project'
      - 'pnpm run build'
      - 'echo #### Deploy Project'
      - 'echo #### Turn Of Alarm Actions'
      - 'aws cloudwatch disable-alarm-actions --alarm-names $ALARM_NAME'
      - 'aws s3 sync ./out s3://$BUCKET_NAME'
      - 'echo #### Turn On Alarm Actions'
      - 'aws cloudwatch enable-alarm-actions --alarm-names $ALARM_NAME'
