version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
      python: $PYTHON_VERSION
    commands:
      - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh"
      - "cd ${CODEBUILD_SRC_DIR}/website"

  build:
    commands:
      - "echo #### Build Project"
      - "make build-out"
      - "echo #### Deploy Project"
      - "echo #### Turn Of Alarm Actions"
      - "aws cloudwatch disable-alarm-actions --alarm-names $ALARM_NAME"
      - "python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/deploy_content.py"
      - "echo #### Invalidate CloudFront Cache"
      - "python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/cache_invalidation.py"
      - "echo #### Turn On Alarm Actions"
      - "aws cloudwatch enable-alarm-actions --alarm-names $ALARM_NAME"
      - "python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/continuous_deployment_switch.py"
