version: 0.2

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      ruby: $RUBY_VERSION
    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/credentials.sh'
      - 'dnf install -y yum-utils'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/terraform_installation.sh'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}/terraform'
      - 'echo ## TERRASPACE PLAN : Generate the Terraform Plan'
      - 'sed -i "s/continuous_deployment_policy_id = aws_cloudfront_continuous_deployment_policy.continuous_deployment_policy.id/#continuous_deployment_policy_id = aws_cloudfront_continuous_deployment_policy.continuous_deployment_policy.id/" terraform/app/modules/aws/cloudfront/main.tf'
      - 'terraspace plan website --out "website.plan"'
      - 'sed -i "s/#continuous_deployment_policy_id = aws_cloudfront_continuous_deployment_policy.continuous_deployment_policy.id/continuous_deployment_policy_id = aws_cloudfront_continuous_deployment_policy.continuous_deployment_policy.id/" terraform/app/modules/aws/cloudfront/main.tf'
      - 'terraspace plan website --out "website_staging.plan"'
artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
