version: 0.2

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
    commands:
      - "python3 ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/py/origin_change.py"
  build:
    commands:
      - "mkdir -p ${CODEBUILD_SRC_DIR}/codepipeline-artifacts"
      - "printf 'release complete\n' > ${CODEBUILD_SRC_DIR}/codepipeline-artifacts/release.txt"

artifacts:
  files:
    - "codepipeline-artifacts/release.txt"
