source_repo_owner           = "VilnaCRM-Org"
source_repo_name            = "website-infrastructure"
source_repo_branch          = "2-set-up-the-frontend-production-infrastructure"
kms_condition_account_value = "Account"
region = "eu-central-1"