version: 0.2

env:
  variables:
    CODE_SRC_DIR: '.'
    TF_VERSION: '1.6.6'
    PYTHON_VERSION: '3.12'
    RUBY_VERSION: '3.2'

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
      ruby: $RUBY_VERSION
    commands:
      - 'export AWS_PROFILE=terraform'
      - 'touch ~/.aws/config'
      - 'echo "[profile ${AWS_PROFILE}]" > ~/.aws/config'
      - 'echo "region = ${AWS_DEFAULT_REGION}" >> ~/.aws/config'
      - 'touch ~/.aws/credentials'
      - 'echo "[${AWS_PROFILE}]" > ~/.aws/credentials'
      - 'echo "aws_access_key_id = $(aws secretsmanager get-secret-value --secret-id test/AWS/Website --query SecretString --output text | jq -r ".WEBSITE_AWS_ACCESS_KEY")" >> ~/.aws/credentials'
      - 'echo "aws_secret_access_key = $(aws secretsmanager get-secret-value --secret-id test/AWS/Website --query SecretString --output text | jq -r ".WEBSITE_AWS_SECRET_KEY")" >> ~/.aws/credentials'
      - 'cat ~/.aws/config'
      - 'cat ~/.aws/credentials'
      # - 'aws configure set aws_access_key_id $(aws secretsmanager get-secret-value --secret-id test/AWS/Website --query SecretString --output text | jq -r ".WEBSITE_AWS_ACCESS_KEY") --profile $AWS_PROFILE'
      # - 'aws configure set aws_secret_access_key $(aws secretsmanager get-secret-value --secret-id test/AWS/Website --query SecretString --output text | jq -r ".WEBSITE_AWS_SECRET_KEY") --profile $AWS_PROFILE'
      # - 'aws configure set default.region $AWS_DEFAULT_REGION --profile $AWS_PROFILE'
      # - 'aws configure set default.output json --profile $AWS_PROFILE'
      - 'yum install -y yum-utils'
      - 'yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo'
      - 'yum -y install terraform'
      - 'bundle install --gemfile ${CODEBUILD_SRC_DIR}/terraform/Gemfile'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}/terraform'
      - 'echo ## TERRASPACE PLAN : Generate the Terraform Plan'
      - 'TF_LOG=DEBUG terraspace all plan --out "tf.plan"'

artifacts:
  files:
    - '**/*'
