name: 'GitHub Token Rotation'

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

jobs:
  rotate-github-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: eu-central-1

      - name: Rotate GitHub Token
        env:
          SECRET_NAME: github-token
        run: |
          echo "Generating new GitHub token..."

          # Authenticate as a GitHub App
          jwt=$(python3 -c "import jwt, time; import os; print(jwt.encode({'iat': int(time.time()), 'exp': int(time.time()) + 600, 'iss': os.environ['GITHUB_APP_ID']}, os.environ['GITHUB_PRIVATE_KEY'].replace('\\n', '\n'), algorithm='RS256'))")

          # Get installation ID
          installation_id=$(curl -s \
            -H "Authorization: Bearer $jwt" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/app/installations | jq -r '.[0].id')

          # Create an installation access token
          token_response=$(curl -s -X POST \
            -H "Authorization: Bearer $jwt" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/app/installations/$installation_id/access_tokens)

          NEW_TOKEN=$(echo $token_response | jq -r '.token')

          # Update AWS Secrets Manager with the new token
          aws secretsmanager put-secret-value --secret-id "$SECRET_NAME" --secret-string "$NEW_TOKEN"

          echo "GitHub token rotated and updated in AWS Secrets Manager."