version: 0.2

env:
  variables:
    PROJECT_NAME: "sandbox-test"
    BRANCH_NAME: "6-implement-sandbox-workflows"
    AWS_DEFAULT_REGION: "eu-central-1"

phases:
  install:
    commands:
      - echo "Listing files in the current directory:"
      - ls -la
  build:
    commands:
      - chmod +x ${CODEBUILD_SRC_DIR}/aws/scripts/sh/sandbox_deletion.sh
      - echo "Run script"
      - . ${CODEBUILD_SRC_DIR}/aws/scripts/sh/sandbox_deletion.sh
      - echo "S3 bucket has been deleted."
      