version: 0.2

phases:
  install:
    commands:
      - echo "Listing files in the current directory:"
      - ls -la
      - echo "Listing files in the scripts directory:"
      - ls -la ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh
  build:
    commands:
      - echo "Fetching all S3 buckets..."
      - cd ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh
      - chmod +x sandbox_deletion.sh
      - ./sandbox_deletion.sh
      - echo "All S3 buckets have been deleted."