version: 0.2

phases:
  install:
    commands:
      - echo "Listing files in the current directory:"
      - ls -la
  build:
    commands:
      - chmod +x ${CODEBUILD_SRC_DIR}/aws/scripts/sh/sandbox_deletion.sh
      - echo "Run script"
      - . ${CODEBUILD_SRC_DIR}/aws/scripts/sh/sandbox_deletion.sh
      - echo "S3 bucket has been deleted."
