version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/sandbox_installation.sh'
      - 'cd /codebuild-user/website'
      - 'sudo dnf install "dnf-command(config-manager)"'
      - 'sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo'
      - 'sudo dnf install gh --repo gh-cli'

  build:
    commands:
      - 'echo #### Build Project'
      - 'make build'
      - 'echo #### Deploy Project'
      - 'aws s3 sync ./out s3://"$PROJECT_NAME-$BRANCH_NAME'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'