version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - '[ -n "$NODEJS_VERSION" ] || { echo "NODEJS_VERSION is not set"; exit 1; }'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/sandbox_installation.sh'
      - 'cd ${WEBSITE_DIR:-/codebuild-user/website}'
      - 'sudo apt update'
      - 'sudo apt install gh -y || { echo "Failed to install GitHub CLI"; exit 1; }'

  build:
    commands:
      - 'echo #### Build Project'
      - 'make build || { echo "Build failed"; exit 1; }'
      - 'echo #### Deploy Project'
      - 'aws s3 sync ./out s3://$PROJECT_NAME-$BRANCH_NAME'
      - 'echo #### Create pull request comment'
      - 'bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'
