version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - "bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/sandbox_installation.sh"
      - "cd ${WEBSITE_DIR:-/codebuild-user/website}"
      - "sudo apt update"
      - 'sudo apt install gh -y || { echo "Failed to install GitHub CLI"; exit 1; }'

  build:
    commands:
      - "echo #### Build Project"
      - 'make build || { echo "Build failed"; exit 1; }'
      - "echo #### Deploy Project"
      - 'aws s3 sync ./out s3://$PROJECT_NAME-$BRANCH_NAME || { echo "S3 sync failed"; exit 1; }'
      - "echo #### Check for bucket creation and decide on PR comment"
      - |
        MARKER_PATH=".markers/bucket_created.txt"
        if aws s3api head-object --bucket $PROJECT_NAME-$BRANCH_NAME --key $MARKER_PATH > /dev/null 2>&1; then
          echo "Bucket was created in this run. Proceeding to create PR comment."
          bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pr_comment.sh
          aws s3 rm s3://$PROJECT_NAME-$BRANCH_NAME/$MARKER_PATH || { echo "Failed to delete marker file"; exit 1; }
        else
          echo "Bucket already existed. Skipping PR comment creation."
        fi
