version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: $NODEJS_VERSION
    commands:
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/website_installation.sh'
      - 'cd /codebuild-user/website'

  build:
    commands:
      - 'echo #### Build Project'
      - 'make build'
      - 'echo #### Deploy Project'
      - 'aws s3 sync ./out s3://$BUCKET_NAME'
