version: 0.2

phases:
  install:
    commands:
      - "echo 'Installing GitHub CLI (gh)...'"
      - "curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo | sudo tee /etc/yum.repos.d/gh-cli.repo"
      - "sudo yum install -y gh"
      - "gh --version"

  build:
    commands:
      - |
        echo "## Running Health Check for Sandbox Bucket..."
        BUCKET_URL="https://${PROJECT_NAME}-${BRANCH_NAME}.s3.${AWS_DEFAULT_REGION}.amazonaws.com"

        if ! curl -sSf "$BUCKET_URL" > /dev/null; then
          echo "Health check failed. Adding comment to PR..."

          if aws secretsmanager get-secret-value --secret-id github-token --query SecretString --output text | gh auth login --with-token; then
            echo "GitHub authentication failed"
            exit 1
          fi

          COMMENT_BODY=":x: Health check failed for the sandbox bucket.
          Please check the CodeBuild logs for detailed error information."

          if ! gh pr comment "$PR_NUMBER" -R "$GITHUB_REPOSITORY" --body "$COMMENT_BODY"; then
            echo "Failed to add error comment to PR"
            exit 1
          fi
          exit 1
        else
          echo "Health check passed. Running create_pr_comment script..."
          bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pr_comment.sh || {
            echo "Failed to execute create_pr_comment.sh"
            exit 1
          }
        fi
