version: 0.2

env:
  variables:
    HURL_VERSION: "4.2.0"
    HURL: "./target/release/hurl-installation"
    HURL_DIR: "./hurl"

phases:
  install:
    commands:
      - "dnf install -y pkg-config gcc openssl-devel libxml2-devel"
      - "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      - "source $HOME/.cargo/env"
      - "rustc --version"
      - "cargo --version"
      - "cargo install hurl"
      - 'sudo apt install gh -y || { echo "Failed to install GitHub CLI"; exit 1; }'

  build:
    commands:
      - |
        echo "## Running Health Check for Sandbox Bucket..."
        BUCKET_URL="https://${PROJECT_NAME}-${BRANCH_NAME}.s3.${AWS_DEFAULT_REGION}.amazonaws.com"
        if ! hurl --test --verbose --variable website_url=$BUCKET_URL ${CODEBUILD_SRC_DIR}/${HURL_DIR}/healthcheck.hurl; then
          echo "Health check failed. Adding comment to PR..."
          aws secretsmanager get-secret-value --secret-id github-token --query SecretString --output text | gh auth login --with-token || {
            echo "GitHub authentication failed"
            exit 1
          }
          COMMENT_BODY=":x: Health check failed for the sandbox bucket.
          Please investigate the issue."
          if ! gh pr comment "$PR_NUMBER" -R "$GITHUB_REPOSITORY" --body "$COMMENT_BODY"; then
            echo "Failed to add error comment to PR"
            exit 1
          fi
          exit 1
        else
          echo "Health check passed. Running —Åreate_pr_comment script..."
          bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pr_comment.sh || {
            echo "Failed to execute create_pr_comment.sh"
            exit 1
          }
        fi
