version: 0.2

env:
  variables:
    HURL_VERSION: "4.2.0"
    HURL_DIR: "./hurl"
    HURL_FILE: "sandbox_healthcheck.hurl"

phases:
  install:
    commands:
      - "echo 'Installing GitHub CLI (gh)...'"
      - "curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo | sudo tee /etc/yum.repos.d/gh-cli.repo"
      - "sudo yum install -y gh"
      - "gh --version"
      - "echo 'Installing Hurl...'"
      - "dnf install -y pkg-config gcc openssl-devel libxml2-devel"
      - "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      - "source $HOME/.cargo/env"
      - "rustc --version"
      - "cargo --version"
      - "cargo install hurl"

  build:
    commands:
      - |
        echo "## Preparing Health Check for S3 Bucket..."
        BUCKET_URL="https://${PROJECT_NAME}-${BRANCH_NAME}.s3.${AWS_DEFAULT_REGION}.amazonaws.com"

        echo "Bucket URL: $BUCKET_URL"

        HURL_FILE_PATH="${CODEBUILD_SRC_DIR}/${HURL_DIR}/${HURL_FILE}"

        echo "## Running Health Check with Hurl..."
        if ! hurl --test --verbose \
          --variable bucket_url="$BUCKET_URL" \
          "$HURL_FILE_PATH"; then
          echo "Health check failed. Adding comment to PR..."

          if ! aws secretsmanager get-secret-value --secret-id github-token --query SecretString --output text | gh auth login --with-token; then
            echo "GitHub authentication failed"
            exit 1
          fi

          COMMENT_BODY=":x: Health check failed for the sandbox bucket.
          Please check the CodeBuild logs for detailed error information."

          if ! gh pr comment "$PR_NUMBER" -R "$GITHUB_REPOSITORY" --body "$COMMENT_BODY"; then
            echo "Failed to add error comment to PR"
            exit 1
          fi
          exit 1
        else
          echo "Health check passed. Running create_pr_comment script..."
          if ! bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pr_comment.sh; then
             echo "Failed to execute create_pr_comment.sh"
             exit 1
          fi
        fi
