version: 0.2

phases:
  install:
    runtime-versions:
      ruby: $RUBY_VERSION
    commands:
      - 'env'
      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/credentials.sh'
      - 'dnf install -y yum-utils'
  build:
    commands:
      - 'cd ${CODEBUILD_SRC_DIR}'
      - 'echo ## TERRASPACE UP : Bringing up the infrastructure'
      - 'make terraspace-up stack="website-sandbox"'
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/bin'
    - '/usr/local/bin'
    - '/root/.terraform'
    - '/root/.cache'
    - '/root/.gem'
    - '/usr/local/bundle'
